### ISSUE TITLE
Add WASI core implementation

### ISSUE THREAD

**Issue by satabin** [satabin/swam#36]
The first version of WASI core library has been published. Add implementation of a meaningful subset of it.

View:
 - https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/
 - https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-api.md

**Comment by Jacarte** [comment]
Moving implementations from [wasi-support PR](https://github.com/satabin/swam/pull/70) to wasi/core branch

**Comment by satabin** [comment]
See #72
