### ISSUE TITLE
How to run wasm files?

### ISSUE THREAD

**Issue by jianguda** [satabin/swam#51]
Hey, I am trying to run wasm files using SWAM, however, I still can not find out how to do it.

Could you please give me some hints (or add to the README)? (such as how to run these files in the `example` folder.) Thanks!

**Comment by satabin** [comment]
Hi,

The example in the `examples` folders are mainly for documentation purpose, however they are executed to generate the examples on the website, so they a complete and can be run if you copy the Scala code. The simplest way would be to extract the code into a `.sc` file, for instance the fibonacci create a file named `fibo.sc` in the root of the project:

```scala
import swam._
import text._
import runtime._
import formats.DefaultFormatters._
import cats.effect._
import java.nio.file.Paths

val tcompiler = Compiler[IO]

val engine = Engine[IO]

def instantiate(p: String): Instance[IO] =
  (for {
    engine <- engine
    tcompiler <- tcompiler
    m <- engine.compile(tcompiler.stream(Paths.get(p), true))
    i <- m.instantiate
  } yield i).unsafeRunSync()

def time[T](t: => T): T = {
  val start = System.currentTimeMillis
  val res = t
  val end = System.currentTimeMillis
  println(s"Time: ${end - start}ms")
  res
}

val i = instantiate("examples/docs/fibo.wat")

val naive = i.exports.typed.function1[Long, Long]("naive").unsafeRunSync()
val clever = i.exports.typed.function1[Long, Long]("clever").unsafeRunSync()
```

Then you can start an interactive sessions with: `./millw -i runtime.test.repl`

At prompt, you can import and evaluate that file with `import $file.fibo`

Now the `fibo` name in the REPL is bound to this file as a module, you can import it to get access to the declared public members in the file (like `time` or `naive` or `clever`): `import fibo._`

You can then use these members and evaluate their result:

```scala
time(naive(30).unsafeRunSync())
time(clever(30).unsafeRunSync())
```

I will see I can document it better, there is no runner for now, this is only a library so requires the glue-code. I am thinking about making a CLI tool out of it to make it easier.

**Comment by jianguda** [comment]
I tested and it works now, thanks!

**Comment by satabin** [comment]
I'll leave this ticket open until I port it into the documentation.

**Comment by shrin18** [comment]
We have succeeded but it is not stable. We are getting the following error:
```
@ import $file.fibo 
cmd0.sc:61: object fibo is not a member of package ammonite.$sess
import ammonite.$sess.{
       ^
Compilation Failed
```

**Comment by satabin** [comment]
That's weird I never encountered that problem. What version of mill and java are you running? Try remove `~/.mill/ammonite` you might have weird stuff in it. What steps did you actually do? I just reproduced what I wrote above and it worked.

**Comment by jianguda** [comment]
We are using `millw` inside SWAM, using `Java 11.0.4` or `Java 1.8.0_222`, and `Scala 2.12.8`.
We just follow steps in this issue, it happens very offen, sometimes it is okay.

**Comment by satabin** [comment]
This is really weird indeed. What OS are you using?

**Comment by jianguda** [comment]
Both of us are using __Ubuntu 18.04.3 LTS__
We can make it run when we remove local repo and pull from GitHub again, but if we try again, we reproduce that error.

**Comment by satabin** [comment]
Ok I have it, this is a bug in ammonite, see lihaoyi/Ammonite#959. You don't need to reclone everything, just remove the cache with `rm -rf out/runtime/test/` at the root of the repository.

**Comment by shrin18** [comment]
Yes it works now. Thanks. We have to remove that file everytime we exit though.

**Comment by satabin** [comment]
Sadly until this is fixed in Ammonite and updated in mill, there is nothing I can do. You can run the standard scala repl, not ammonite, by doing. So if you have the fibo.sc file above you can do as in this session asciinema: [![asciicast](https://asciinema.org/a/bdk6Cc5xoUH4Acb0LxvARMj4G.svg)](https://asciinema.org/a/bdk6Cc5xoUH4Acb0LxvARMj4G)

**Comment by shrin18** [comment]
Thanks for the help @satabin

**Comment by Jacarte** [comment]
Hi @satabin, I tried a few moments ago, and it's not working now. Probably, something changed in the snippet after the refactoring. 

Thanks!

**Comment by satabin** [comment]
There is now a CLI tool contributed by @Jacarte, so I think I can close this issue. Let me know if you still have a problem.
