### ISSUE TITLE
How to get the start function in the WASM module? 

### ISSUE THREAD

**Issue by Jacarte** [satabin/swam#62]
For example, can this variable be public ?
https://github.com/satabin/swam/blob/b570dc2be8ceeb3f5d9537e8794ce559a7327c29/runtime/src/swam/runtime/Module.scala#L46

**Comment by satabin** [comment]
Hi @Jacarte what is you use case? The rationale behind what is public or not here is: is it exported by the module. The start function is kind of an internal thing.

**Comment by Jacarte** [comment]
Thanks for the answer, now its clear.
