### ISSUE TITLE
How to run the wasm file in a custom project referenceing swam apis from Scala sbt

### ISSUE THREAD

**Issue by tareq97** [satabin/swam#69]
Hi @satabin,

Actually I wanted to run the wasm file using in the scala project which I have created so I have loaded the three swam API from the link(https://search.maven.org/artifact/org.gnieh/swam-core_2.13/0.5.0/jar) provided on the website. I am trying to use the example program which is mentioned in swam package website(https://swam.gnieh.org/api/swam/runtime/index.html). 
In that example, there is a line where wasm file is supposed to compile 
```engine.compile(/* source of the module */)```
But there are three overloaded methods of which I wanted to use the below mentioned method.
```
engine.compile(Path, Blocker, chucksize)
```
Path: Here I am passing wasm file path. But I am not aware what other arguments do
Blocker: ??? Want to get clarification on what to pass in the place of Blocker and chunk size.
chuck size = By default is 1024

![Engine compile_method](https://user-images.githubusercontent.com/10094302/78128339-01694480-7416-11ea-871a-439666511254.png)

The requirement is such that I want to run the compile method only by using the path of the wasm and not by the reading it in bytes or section form.

**Comment by satabin** [comment]
Hi @tareq97,

The `Blocker` is something from [cats-effect](https://typelevel.org/cats-effect/datatypes/contextshift.html#blocker) which ensures that the I/O bound operations are not run from within a CPU bound execution context.

Good that you pointed out that the example is not correct anymore. I already updated the examples in the 0.6.0 release to come, but I still need to fix this one.

In your case, you can have a look at the [fibonacci example](https://github.com/satabin/swam/blob/master/examples/docs/fibo.md) for instance, where I added this `Blocker`.

**Comment by satabin** [comment]
By the way, the `tcompiler` is the text-form to wasm compiler. You only need it if the WebAssembly module you are loading is in the text form. If it is in binary form, then you don't need it.

**Comment by satabin** [comment]
@tareq97 hey, did you sole your problem here? Can I close the ticket?

**Comment by tareq97** [comment]
Yes This can be closed
