### ISSUE TITLE
./millw _._ fails: benchmarks.finalMainClass No main class specified or found

### ISSUE THREAD

**Issue by orestisfl** [satabin/swam#81]
## What I did

```shell
$ ./millw _._
[30/535] core.compile 
Compiling compiler interface...
9 warnings
[info] Compiling 47 Scala sources to /home/orestis/KTH/SLUMPs/swam/out/core/compile/dest/classes ...
[info] Done compiling.
[53/535] runtime.compile 
[info] Compiling 47 Scala sources to /home/orestis/KTH/SLUMPs/swam/out/runtime/compile/dest/classes ...
[info] Done compiling.
[72/535] benchmarks.compile 
[info] Compiling 3 Scala sources to /home/orestis/KTH/SLUMPs/swam/out/benchmarks/compile/dest/classes ...
[info] Done compiling.
[92/535] benchmarks.generateBenchmarkSources | Downloading [8/8] artifacts (~50940/50940 bytes)
Processing 31 classes from /home/orestis/KTH/SLUMPs/swam/out/benchmarks/compile/dest/classes with "reflection" generator
Writing out Java source to /home/orestis/KTH/SLUMPs/swam/out/benchmarks/generateBenchmarkSources/dest/jmh_sources and resources to /home/orestis/KTH/SLUMPs/swam/out/benchmarks/generateBenchmarkSources/dest/jmh_resources
[98/535] benchmarks.finalMainClass 
1 targets failed
benchmarks.finalMainClass No main class specified or found
```

Attaching the resulting out folder (GH attachments have a 10mb limit): https://github.com/orestisfl/swam/commit/d0fb321989c1d6832e7962c6ec558a42394cb3a4

Environment:
```
$ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode
$ ./millw --version
Mill Build Tool version 0.7.0
Java version: 14.0.1, vendor: N/A, runtime: /usr/lib/jvm/java-14-openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "Linux", version: 5.7.7-arch1-1, arch: amd64
```

**Comment by satabin** [comment]
What are you trying to do? The command `mill _._` means execute all commands on all module (`_` is a wildcard for mill), so when trying to execute the `run` command on the benchmark module, it fails because no main class exists.

**Comment by orestisfl** [comment]
I see, maybe this was pointless then.

Is there a way to specify that a target does not have a `.run` command? What would be the idiomatic way to "do everything"?

**Comment by satabin** [comment]
I don't know of idiomatic way of doing everything since I am not sure what this everything should be.

If you want to test all the modules (and their submodules), you can do:
`mill __.test`

(note the 2 `_` which is the recursive wildcard)

running cannot be really done meaningfully for everything since there is only one module that has a main class to run, `cli`: `mill cli.run`

Basically I would advise you to always give the command you want to run, and potentially use wildcards for modules.

**Comment by orestisfl** [comment]
I see. Thank you!
