### ISSUE TITLE
Wrong exit code 99 with program that should work

### ISSUE THREAD

**Issue by orestisfl** [satabin/swam#89]
## What I did

Extract this [box.zip](https://github.com/satabin/swam/files/4901667/box.zip) in the cwd and run:

```shell
$ java -jar out/cli/assembly/dest/out.jar run --wasi --dir=. box # exit code 99
# or
$ ./millw cli.run run --wasi --dir=. box
1 targets failed
cli.run subprocess failed
```

Wasmer executes this successfully and returns 0

**Comment by satabin** [comment]
Testing locally, this shows that this is the value passed to the `proc_exit` call. According to the WASI documentation this must be the process return code, so it looks like this is the intended behavior (according to doc). I don't know what wasmer does (maybe it ignores this value?), but I would follow the WASI documentation, not wasmer.

**Comment by satabin** [comment]
A return code of `99` seems to mean that the sodium lib could not be properly initialized. The reason why is unknown to me so far and I can't really investigate this. Maybe it requires some WASI features not implemented in swam yet. Maybe it's something else.

**Comment by orestisfl** [comment]
After investigating a bit, it seems to fail at this line:
https://github.com/jedisct1/libsodium/blob/d1d777532fecc42a2e04f7bca3ec43f4481921c2/test/default/cmptest.h#L199-L203

which seems to be the equivalence checking

**Comment by orestisfl** [comment]
So, the linked loop is a byte by byte comparison. With swam, the test fails in the first iteration. `fgetc(fp_res)` returns `-1` (EOF), while `fgetc(fp_out)` returns the first byte correctly.

Before to the comparison `fp_res` is:
1. Opened
2. Flushed: `fflush(fp_res);`
3. Rewinded: `rewind(fp_res);`

Removing steps 2. and 3. seems to result in the same problem.

So, this seems like a WASI problem after all.

**Comment by satabin** [comment]
Yep, swam problem but not in the `proc_exit`, I will check the implementation of the other WASI file operations.

**Comment by orestisfl** [comment]
MWE of the problem:

```c
#include <stdio.h>
#include <stdlib.h>

int main(void) {
  FILE *fp = fopen("a.txt", "w+");
  if (!fp) {
    return 1;
  }

  fprintf(fp, "Hello world!\n");

  fflush(fp);
  rewind(fp);
  int chr = fgetc(fp);
  printf("%d\n", chr);
}
```

In native this prints 72, with swam you get -1 (EOF)
